### ISSUE TITLE
takenSeats should be added to realTimeData

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#74]
as discussed with other groups and mentioned [here](https://github.com/GSE-Project/SS2016-group2/wiki/Interface-meeting-RequestStops)
- [x] update the wiki interface
- [x] clarify the output of busses/{id} with group1/2
- [ ] update the code output
- [ ] clarify how the updating of number of seats would happen
- [ ] update the code input

**Comment by razadfki** [comment]
@mbaniasad I'm going to work on this issue if you're not doing?

**Comment by mbaniasad** [comment]
@razadfki it would need a bit of clarification
my assumption is this now.
1- every time the bus app sends the realTimeData it would send the number of taken seats as well.
2- we would save this number with other realTimeData.
3- the citizen asks for realTimeData of the bus in "busses/1" for example
4- he would get current realTimeData which would have the number of taken seats as well

**Comment by razadfki** [comment]
then, we have to modify the **realTimeData** interface first to incorporate this **occupied or available** seats property. And I see a problem i.e., **realTimeData** updates last position of the bus and takes busId and position coordinates, so now every time it takes no.of seats as well (if you know what I mean)?
For example, Stop A to B, bus sends its location information 10 times then we're getting 10 times this seat property as well even though its not changing? :-/

**Comment by mbaniasad** [comment]
updated the [interface](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces/_compare/f8743d8e16af8e822952df3ec1d2bb1985bf71b8...1b00e05fb1ca94301db7cefe02e6d9e559714887)

**Comment by razadfki** [comment]
@mbaniasad I'm confused now, can you please elaborate a little what do you mean by:
_**update the code output/input?
and where to clarify?**_
from the checklist you created above.

**Comment by razadfki** [comment]
@mbaniasad  one more thing shouldn't it be _**availableSeats**_ instead of _**takenSeats**_
![availableSeats](https://cloud.githubusercontent.com/assets/18569477/16192351/14300fd6-36e9-11e6-9959-dd9ba89e2deb.PNG)

**Comment by mbaniasad** [comment]
@razadfki takenSeats is agreed upon. I don't see the difference between taken or available
since both are calculate able considering  that the number of all seats in a bus is available  
second I would say counting the number of people in the bus is easier for driver then counting them an subtracting it from the number of seats in the bus

**Comment by razadfki** [comment]
no driver will only tell the number of people in the bus. It's the server who calculates the available seats by subtracting takenSeats from the totalSeats of the bus property. it was the idea I was talking about otherwise I've committed it because what was required in the requirement is done.

**Comment by mbaniasad** [comment]
I still don't get your point. we can talk about it when we have the time

**Comment by razadfki** [comment]
@mbaniasad , sure! we will talk about it and also should it be reopen and move to the 4th iteration as we talked yesterday?
